<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ColdFusion MCP Server Test Client</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }
        .panel {
            background: white;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1, h2 {
            color: #333;
        }
        button {
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin: 5px;
        }
        button:hover {
            background-color: #0056b3;
        }
        #status {
            padding: 10px;
            margin: 10px 0;
            border-radius: 4px;
        }
        .connected { background-color: #d4edda; color: #155724; }
        .disconnected { background-color: #f8d7da; color: #721c24; }
        #log {
            height: 400px;
            overflow-y: auto;
            background: #f8f9fa;
            padding: 10px;
            border-radius: 4px;
            font-family: monospace;
            font-size: 12px;
        }        .log-entry {
            margin: 5px 0;
            padding: 5px;
            border-bottom: 1px solid #ddd;
        }
        input[type="text"] {
            width: 100%;
            padding: 8px;
            margin: 5px 0;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <h1>ColdFusion MCP Server Test Client</h1>
    
    <div id="status" class="disconnected">Disconnected</div>
    
    <div class="container">
        <div class="panel">
            <h2>Controls</h2>
            <button onclick="connect()">Connect</button>
            <button onclick="disconnect()">Disconnect</button>
            <button onclick="initialize()">Initialize</button>
            <button onclick="listTools()">List Tools</button>
            
            <h3>Test Hello Tool</h3>
            <input type="text" id="helloName" placeholder="Enter name" value="ColdFusion Developer">
            <button onclick="callHello()">Call Hello Tool</button>
            
            <h3>Test Database Tool</h3>
            <input type="text" id="dbQuery" placeholder="SQL Query" value="SELECT * FROM example_data LIMIT 10">
            <input type="text" id="dbDatasource" placeholder="Datasource" value="mcpcfc_ds">
            <button onclick="callDatabase()">Execute Query</button>
            
            <h3>Test PDF Generation</h3>
            <textarea id="pdfHtml" placeholder="HTML content" style="width: 100%; height: 100px;">
<h1>Test PDF Document</h1>
<p>This is a test PDF generated by ColdFusion MCP Server.</p>
<ul>
    <li>Feature 1: PDF Generation</li>
    <li>Feature 2: Text Extraction</li>
    <li>Feature 3: PDF Merging</li>
</ul>
<p>Generated on: <cfoutput>#dateFormat(now(), "mm/dd/yyyy")#</cfoutput></p>
            </textarea>
            <input type="text" id="pdfFilename" placeholder="Filename" value="test.pdf">
            <button onclick="generatePDF()">Generate PDF</button>
            
            <h3>Extract PDF Text</h3>
            <input type="text" id="extractPdfPath" placeholder="PDF filename (e.g., test.pdf)" value="test.pdf">
            <button onclick="extractPDFText()">Extract Text</button>
            
            <h3>Merge PDFs</h3>
            <input type="text" id="mergePdf1" placeholder="First PDF (e.g., test.pdf)" value="test.pdf">
            <input type="text" id="mergePdf2" placeholder="Second PDF (e.g., test2.pdf)" value="test2.pdf">
            <input type="text" id="mergeOutput" placeholder="Output filename" value="merged.pdf">
            <button onclick="mergePDFs()">Merge PDFs</button>
            
            <h3>Test Email Tools</h3>
            <input type="text" id="emailTo" placeholder="To" value="test@example.com">
            <input type="text" id="emailSubject" placeholder="Subject" value="Test Email from MCPCFC">
            <textarea id="emailBody" placeholder="Email body" style="width: 100%; height: 60px;">This is a test email sent from the ColdFusion MCP Server!</textarea>
            <button onclick="sendEmail()">Send Plain Email</button>
            <button onclick="sendHTMLEmail()">Send HTML Email</button>
            
            <h3>Validate Email</h3>
            <input type="text" id="validateEmail" placeholder="Email to validate" value="user@example.com">
            <button onclick="validateEmail()">Validate Email</button>
        </div>
        
        <div class="panel">
            <h2>Log</h2>
            <button onclick="clearLog()">Clear Log</button>
            <div id="log"></div>
        </div>
    </div>

    <script>
        let sessionId = null;

        function log(message, data = null) {
            const logDiv = document.getElementById('log');
            const entry = document.createElement('div');
            entry.className = 'log-entry';
            const timestamp = new Date().toLocaleTimeString();
            entry.innerHTML = `<strong>[${timestamp}]</strong> ${message}`;
            if (data) {
                entry.innerHTML += '<pre>' + JSON.stringify(data, null, 2) + '</pre>';
            }
            logDiv.appendChild(entry);
            logDiv.scrollTop = logDiv.scrollHeight;
        }

        function updateStatus(active) {
            const status = document.getElementById('status');
            if (active) {
                status.className = 'connected';
                status.textContent = `Session Active (${sessionId})`;
            } else {
                status.className = 'disconnected';
                status.textContent = 'No Session';
            }
        }

        async function connect() {
            sessionId = crypto.randomUUID();
            log(`Starting session ${sessionId}...`);
            log('Sending initialize request...');

            try {
                const data = await sendRequest('initialize', {
                    protocolVersion: '2025-11-25',
                    capabilities: {},
                    clientInfo: { name: 'mcpcfc-test-client', version: '2.0.0' }
                });
                if (data && !data.error) {
                    updateStatus(true);
                    log('Session initialized', data);
                } else {
                    log('Initialize failed', data);
                    sessionId = null;
                    updateStatus(false);
                }
            } catch (error) {
                log('Connection error: ' + error.message);
                sessionId = null;
                updateStatus(false);
            }
        }

        function disconnect() {
            if (sessionId) {
                log(`Session ${sessionId} ended`);
                sessionId = null;
                updateStatus(false);
            }
        }

        async function sendRequest(method, params = {}) {
            if (!sessionId) {
                log('Error: No active session. Click Connect first.');
                return;
            }

            const url = `/mcpcfc/endpoints/mcp.cfm?sessionId=${sessionId}`;
            const request = {
                jsonrpc: '2.0',
                id: crypto.randomUUID(),
                method: method,
                params: params
            };

            log(`Sending ${method} request`, request);

            try {
                const response = await fetch(url, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-Session-ID': sessionId
                    },
                    body: JSON.stringify(request)
                });

                const data = await response.json();
                log(`${method} response`, data);
                return data;
            } catch (error) {
                log(`Error sending ${method}: ${error.message}`);
            }
        }

        function initialize() {
            sendRequest('initialize', {
                protocolVersion: '2025-11-25',
                capabilities: {},
                clientInfo: { name: 'mcpcfc-test-client', version: '2.0.0' }
            });
        }

        function listTools() {
            sendRequest('tools/list');
        }
        function callHello() {
            const name = document.getElementById('helloName').value;
            sendRequest('tools/call', {
                name: 'hello',
                arguments: { name: name }
            });
        }

        function callDatabase() {
            const query = document.getElementById('dbQuery').value;
            const datasource = document.getElementById('dbDatasource').value;
            sendRequest('tools/call', {
                name: 'queryDatabase',
                arguments: { 
                    query: query,
                    datasource: datasource
                }
            });
        }
        
        function generatePDF() {
            const html = document.getElementById('pdfHtml').value;
            const filename = document.getElementById('pdfFilename').value;
            sendRequest('tools/call', {
                name: 'generatePDF',
                arguments: {
                    html: html,
                    filename: filename
                }
            });
        }
        
        function extractPDFText() {
            const pdfPath = document.getElementById('extractPdfPath').value;
            sendRequest('tools/call', {
                name: 'extractPDFText',
                arguments: {
                    pdfPath: pdfPath
                }
            });
        }
        
        function mergePDFs() {
            const pdf1 = document.getElementById('mergePdf1').value;
            const pdf2 = document.getElementById('mergePdf2').value;
            const output = document.getElementById('mergeOutput').value;
            sendRequest('tools/call', {
                name: 'mergePDFs',
                arguments: {
                    sourcePaths: [pdf1, pdf2],
                    outputPath: output
                }
            });
        }
        
        function sendEmail() {
            const to = document.getElementById('emailTo').value;
            const subject = document.getElementById('emailSubject').value;
            const body = document.getElementById('emailBody').value;
            sendRequest('tools/call', {
                name: 'sendEmail',
                arguments: {
                    to: to,
                    subject: subject,
                    body: body
                }
            });
        }
        
        function sendHTMLEmail() {
            const to = document.getElementById('emailTo').value;
            const subject = document.getElementById('emailSubject').value;
            const body = document.getElementById('emailBody').value;
            const htmlBody = `<html><body><h2>${subject}</h2><p>${body}</p><hr><p><em>Sent from ColdFusion MCP Server</em></p></body></html>`;
            sendRequest('tools/call', {
                name: 'sendHTMLEmail',
                arguments: {
                    to: to,
                    subject: subject,
                    htmlBody: htmlBody,
                    textBody: body
                }
            });
        }
        
        function validateEmail() {
            const email = document.getElementById('validateEmail').value;
            sendRequest('tools/call', {
                name: 'validateEmailAddress',
                arguments: {
                    email: email
                }
            });
        }

        function clearLog() {
            document.getElementById('log').innerHTML = '';
        }

        // Ready on load
        window.addEventListener('load', () => {
            log('Test client ready (HTTP mode). Click "Connect" to start a session.');
        });
    </script>
</body>
</html>